services:
  lazydocker:
    build: .
    container_name: lazydocker
    restart: unless-stopped
    ports:
      - "7681:7681"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.yml:/root/.config/lazydocker/config.yml
      - /run/user/1000/docker.sock:/var/run/docker.sock
